# @name get-prompts

GET http://localhost:3333/prompts

###

# @name upload
POST  http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# @name create-trancription
POST http://localhost:3333/videos/24782005-61a6-439f-8b07-404a4f0f36ac/transcription
Content-Type: application/json

{
  "prompt" : "zé da manga"
}

### 

# @name genarate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoID" : "24782005-61a6-439f-8b07-404a4f0f36ac",
  "temperature" : "0.5",
  "template":"Gere um resumo sucinto da tranquição do vídeo informada a seguir"
}