# @name get-prompts

GET http://localhost:3334/prompts

###

# @name upload
POST  http://localhost:3334/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# @name create-trancription
POST http://localhost:3334/videos/08bfd43e-ecb9-4903-b6d8-e93ffdcc1208/transcription
Content-Type: application/json

{
  "prompt" : "Another Hero,behind the curtain"
}